lb_name                   = "turnit-lb-staging"
ec2_security_group_name   = "turnit-backend-ec2-sg-staging"
ecs_execution_role_name   = "turnit-backend-ecsexecution-role-staging"
ecs_task_role_name        = "turnit-backend-ecstask-role-staging"
codedeploy_role_name      = "turnit-backend-code-deploy-iam-staging"
ec2_instance_profile_name = "turnit-backend-ec2-instance-profile-staging"
route53_zone_name         = "staging.useturnit.com"
host_name                 = "config.staging.useturnit.com"
